### PR TITLE
Update image link to Types visual

### LINKED ISSUE #319: Ch. 5. Broken link (Twitter)
Hello 👋 , just a small issue:

In chapter 5, section `Newtypes`, the link in the sentence: 
```
This design principle is perhaps better communicated visually.
```
seems to be broken (tweet removed I guess).

The link itself is: https://twitter.com/jusrin00/status/875238742621028355/photo/1

Would be cool to either point to the new location of the image (seems like it was the tweet of an image) or remove the reference.

Cheers!

### PR DESCRIPTION
**Pull request by milesfrain**
Fixes #319

### CODE REVIEW

**Review by camimora — APPROVED** [review]
Great! 👍

**Review by camimora — COMMENTED** [review]
Seems like 
`https://raw.githubusercontent.com/justinwoo/my-twitter-memes/master/images/DCV46-aXUAEOnqf.jpg` was working yesterday but is not working today? 🤔

**Comment by milesfrain** [comment]
Looks like that repo disappeared.

So guessing the only next step is to just delete that line in the book. If the original author wants to re-upload, I'd be happy to restore a link, since I think it adds a nice bit of relevant humor to this section.

**Comment by milesfrain** [comment]
Closing in favor of #321

**Comment by camimora** [comment]
> Looks like that repo disappeared.
> 
> So guessing the only next step is to just delete that line in the book. If the original author wants to re-upload, I'd be happy to restore a link, since I think it adds a nice bit of relevant humor to this section.

Agree, is definitely something good to have it in the book but if the link is broken then better to delete the link completely.
Thanks for addressing the issue :) .

**Comment by milesfrain** [comment]
The original image for context:
DCV46-aXUAEOnqf

**Pull request closed without merging**
