### PR TITLE
Add publish date on CI

### PR DESCRIPTION
**Pull request by andys8**
## Description

This PR is supposed to add the information about when the book was published to the hosted version on <https://book.purescript.org>.

## Motivation

Because of the history of the book, I personally always had the feeling that I'm looking at an outdated version. Having some indicator might be helpful that one is indeed looking at an up-to-date copy of the (awesome!) book.

## Technical Considerations

The current PR is super simple. It will add a single line. It is mostly untested on CI, btw. I have no right to execute the github action, so testing wasn't really possible.

### Alternatives

There is also https://github.com/badboy/mdbook-last-changed. It will add a footer to every page and, by default, refer to commits. This might be helpful, but is not actually what I'd intend with this PR. Therefore, I went with the simpler command-line approach, where the result was more to my liking.

### CODE REVIEW

**Comment by Zelenya** [comment]
Awesome. Let's try it. Approving the run

**Comment by andys8** [comment]
CI Test

image

**Comment by andys8** [comment]
## Update

Changed CI to append more information. I'm open to any text or structural changes. Currently it would look like this.

```markdown
## Version

PureScript v0.15.4

Last update on 2023-08-26
```


image

**Comment by Zelenya** [comment]
If there's no simple way of getting the PureScript version, maybe we can be vague about it? The goal is to tell people that the book isn't stale. Something like `The book is kept up to date; see package.yaml (link) for the ...`?

**Comment by andys8** [comment]
> If there's no simple way of getting the PureScript version, maybe we can be vague about it?

Either vague or referring to the one the tests and CI are executed with.
953e01750911cfbfbcda2134a9690e193511fb0c

**Comment by Zelenya** [comment]
Oh, ok, it's just added a 3s

**Comment by Zelenya** [comment]
Looks good to me, @milesfrain what do you think?

**Review by milesfrain — APPROVED** [review]

**Comment by andys8** [comment]
So, who's going to merge? 😉

**Comment by Zelenya** [comment]
Thank you, Andy! Works as expected.

**Pull request merged**
