### PR TITLE
Ch 4: test solutions

### PR DESCRIPTION
**Pull request by oldfartdeveloper**
Issue #99

This and PR #106 should be merged together.

### CODE REVIEW

**Comment by milesfrain** [comment]
> For Review Only 
> Need to wait for another PR (to be created)

I converted this to a draft PR. [Instructions here](https://github.community/t5/How-to-use-Git-and-GitHub/Feature-Request-Switch-from-ready-to-draft-in-pull-requests/m-p/54192#M11480) for reference.

**Comment by milesfrain** [comment]
When #104 merges, we'll apply the edits from #107. We can do this a few ways:
* Just merge #107 (you'll share author credit on commits)
* Copy changes from #107 into this PR. That might be tedious. I don't need authorship credit on these minor edits.
* Overwrite the PR in this `solutions` branch with a force push of the content in #107. Either you or I could force push.

Let me know your preference.

**Comment by oldfartdeveloper** [comment]
@milesfrain Your 1st suggestion seems easiest and is fine with me.  Go ahead with that.

**Comment by milesfrain** [comment]
merged #107

**Pull request closed without merging**
