### PR TITLE
LiveBook

### PR DESCRIPTION
**Pull request by s0kil**
Livebook page as discussed in https://github.com/purescript-contrib/purescript-book/issues/48#issuecomment-612687863

- Renders the Markdown pages in browser
- Use browser print functionality to save as PDF

[Preview](https://s0kil.github.io/purescript-book/book/)

### CODE REVIEW

**Comment by milesfrain** [comment]
I think this looks good. Will wait a few hours for others to provide feedback before merging.

**Comment by s0kil** [comment]
Should be good now, refactored for browser to render the total markdown once versus fourteen times.

**Comment by flip111** [comment]
Can you generate the PDF and put it as download link at the top ?

**Comment by flip111** [comment]
Can you at a table of contents at the top. Possibly also an index at the end?

**Comment by milesfrain** [comment]
I don't have admin access to this repo for configuring gh-pages hosting, but could add either of these links to the main readme:

1. Host HTML through 3rd party:
https://raw.githack.com/s0kil/purescript-book/master/book/index.html
https://raw.githack.com/purescript-contrib/purescript-book/master/book/index.html

The `raw` subdomain can be replaced with `rawcdn` for heavier traffic, but URLs need to contain a SHA or tag because they are cached for a year. Traffic seems low enough to just use the throttled dev hosting for now.

2. Point to your your gh-pages host:
https://s0kil.github.io/purescript-book/book/

Should be fine with tracking `.md` updates, but we'll need to deliver any additional `.html` updates to your repo.

**Comment by milesfrain** [comment]
> Can you generate the PDF and put it as download link at the top ?

@flip111 What are the advantages of PDF over offline web page?

**Comment by s0kil** [comment]
We could add client side HTML to PDF generation, I have tested it, and the result PDF is not rendered as well versus using the browser built-in save as PDF functionality. Is this something we should pursue?

**Comment by flip111** [comment]
> @flip111 What are the advantages of PDF over offline web page?

It's easier to open most of the time. But anyway i would just like something downloadable.

> Is this something we should pursue?

Better a server side solution. But let's see first about a downloadable html.

**Comment by hdgarrood** [comment]
This looks great! I'd be happier hosting it under `purescript.org` though, and using the HTML files in this repo. I can set up DNS and GH pages so that it is available under `book.purescript.org` if that sounds okay?

**Comment by hdgarrood** [comment]
I've now set up DNS and GH pages so that it should be available under `book.purescript.org`. However TLS doesn't seem to be working (yet). GitHub help says it might take an hour or so.

**Comment by dwhitney** [comment]
AMAZING!

**Comment by s0kil** [comment]
TLS is set up now. Is it better for the sub-domain to point to https://book.purescript.org/book instead?

**Comment by hdgarrood** [comment]
Yes, I'd suggest the following:
- Move `book/index.html` in this repo to just `index.html` so that the book can be read at https://book.purescript.org rather than https://book.purescript.org/book (which is a bit repetitive)
- Update the link in the readme to point to https://book.purescript.org
- Update index.html to include the table of contents, as it does in @s0kil's repo
- Update index.html to pull in the readme from this repo before the table of contents?

**Comment by s0kil** [comment]
It would be more clear if the https://book.purescript.org/ would be linked in the repository description.

**Comment by JordanMartinez** [comment]
> Update index.html to pull in the readme from this repo before the table of contents?

If that was done, the book summary I added to the Readme in #72 would display twice.

**Comment by flip111** [comment]
Can it be made that the introduction now found at https://book.purescript.org/ becomes part of the book itself ? So that you land immediately on the book when you go to https://book.purescript.org/

**Comment by hdgarrood** [comment]
Right, I mean instead of the hardcoded text which is there currently.

**Comment by s0kil** [comment]
The PR that is currently open implements the changes described.

**Comment by JordanMartinez** [comment]
Merged it!

**Pull request merged**
