### PR TITLE
Change `Applicative` to `Apply`

### PR DESCRIPTION
**Pull request by ursi**
#184

### CODE REVIEW

**Comment by milesfrain** [comment]
Thanks.
I believe there are a few other mentions of `Applicative` to change further down in this section.
Would comment on those directly if that was allowed by GH. https://github.com/isaacs/github/issues/284

**Comment by ursi** [comment]
@milesfrain is there any more I missed?

**Comment by milesfrain** [comment]
Looks great. Thanks.
FYI, You may want to read Ch12 next, rather than Ch9. We're planning on swapping their orders after closing more issues relating to those two chapters.

**Comment by ursi** [comment]
oh, interesting, well I actually skipped chapter 9 and haven't finished 12 yet so looks like I made the right call.

**Comment by milesfrain** [comment]
Hopefully the `Aff` content in Ch10 isn't too confusing without the background on `Aff` from Ch12.

**Pull request merged**
