### PR TITLE
Ch 7 Sample text typos

### PR DESCRIPTION
**Pull request by oldfartdeveloper**
@milesfrain Looks like these were reintroduced recently.

### CODE REVIEW

**Comment by oldfartdeveloper** [comment]
Changed to "Draft"; need to check things out a bit.

**Comment by oldfartdeveloper** [comment]
No, I think @milesfrain is serious about the `R` so closing for now.

**Comment by oldfartdeveloper** [comment]
Wait, have to keep the other commit; reopening

**Comment by milesfrain** [comment]
Good catch.

> Looks like these were reintroduced recently.

`git blame` shows that these lines have been around for the past 4 years.
https://github.com/purescript-contrib/purescript-book/blame/master/text/chapter7.md#L578

We fixed some of these in #128, but didn't get all of them. There are still a few of these typos remaining in this file. Could you fix those too?

**Comment by oldfartdeveloper** [comment]
Ahh, it seemed to me that we had fixed these as part of the `newType` changes you made; I figured some of them crept back.  In any case I found 2 more and submitted a 2nd commit; are those the ones you were thinking of?

The chapter is reading much easier and figuring out what I should do on the exercises is vastly enhanced by you specifying the function name and having the unit test code.  Before they were just too vague.

I'll attempt to follow your examples in my unit test writing for ch 8.

**Pull request merged**
