### PR TITLE
tests for Monad Comprehensions and backtracking

### PR DESCRIPTION
**Pull request by marcellourbani**
Just added a couple of tests that was missing and relative sample code
Had to name a couple of functions to do that

### CODE REVIEW

**Comment by marcellourbani** [comment]
I'm a bit confused: spago build works on my machine. Will add the offending package and try again

**Comment by marcellourbani** [comment]
[ran the build](https://github.com/marcellourbani/purescript-book/pull/1/checks?check_run_id=3233651490) on my own repo this time, it's working now

**Comment by milesfrain** [comment]
> I'm a bit confused: spago build works on my machine.

I suspect this is due to running a pre-0.20.0 version of spago on your machine. Some more explanation can be found in https://github.com/purescript/spago/issues/769

Thanks for adding these tests! I'll take a closer look at these book PR in the next few days.

**Comment by marcellourbani** [comment]
Was indeed 0.19
Guess import worked due to transient dependencies

**Pull request merged**
