### PR TITLE
Fix scripts/removeAnchors.sh on Mac

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Comment by keithlayne** [comment]
Neither the built-in `find` nor GNU `find` seem to recognize that flag on my Mac.

**Comment by cblp** [comment]
It's strange, I see the same options as in https://www.unix.com/man-page/FreeBSD/1/find/

MacOS 11.6

**Comment by stackcats** [comment]
I can use this version on my Mac.

**Comment by keithlayne** [comment]
Must have been user error on my part, confirm it works with `/usr/bin/find` on my mac. But GNU find doesn't recognize that flag, so it's not going to work on linux. 

I don't think anyone should have to worry about this - I have another suggestion in #396.

**Comment by milesfrain** [comment]
Unfortunately, `find -E` doesn't work on linux.

We could add a conditional in that script to check for machine type.

We should also add a CI target for Mac. PR's welcome for that addition.

I also like some of the ideas proposed in #396.

**Pull request closed without merging**
