### PR TITLE
Travis-CI for mdbook and gh-pages

### PR DESCRIPTION
**Pull request by milesfrain**
Here is an example of the [Travis job](https://travis-ci.org/github/milesfrain/purescript-book/builds/674997913) running on my [travis-demo branch](https://github.com/milesfrain/purescript-book/commit/5afb867d893db5cd9d7bfa85f3e22dc197338606).

Preview: https://milesfrain.github.io/purescript-book/

The only difference with this PR is the removal [these lines](https://github.com/milesfrain/purescript-book/commit/5afb867d893db5cd9d7bfa85f3e22dc197338606#diff-354f30a63fb0907d4ad57269548329e3R13-R14) to default to master branch:
```
  on:
    branch: travis-demo # Will default to master branch if on.branch is removed
```

The remaining configuration steps are:
* ~~[Activate travis on this repo](https://travis-ci.com/github/purescript-contrib/purescript-book).~~ Edit: Already running on travis-ci.**com** (previously liked to inactive travis-ci.**org** instance ... confusing).
* Generate and add [github token](https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token) to Travis repo.
* Whatever else might be needed for compatibility with a custom domain name: [book.purescript.org](https://book.purescript.org/)

@hdgarrood we could use your help with these administrative tasks.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Can I request that we use [dplv2 with a deploy key](https://docs.travis-ci.com/user/deployment-v2/providers/pages/)? That way if the key does get compromised somehow it will only be able to modify this repository, whereas if a personal access token is compromised then the attacker would be able to modify any repository the owner of the token has access to.

**Comment by milesfrain** [comment]
> Can I request that we use [dplv2 with a deploy key](https://docs.travis-ci.com/user/deployment-v2/providers/pages/)?

Sounds good. Updated PR

**Comment by hdgarrood** [comment]
I guess we (I) will need to change the github pages configuration for this repo so that it uses the `gh-pages` branch for the site rather than the `master` branch, as it does currently. I'll do that once this PR is merged and the auto deployment has successfully built the book and pushed it to the `gh-pages` branch.

**Comment by milesfrain** [comment]
@hdgarrood Looks like there was an issue with the deploy key.
https://travis-ci.com/github/purescript-contrib/purescript-book/builds/160480788
I don't have access to the repository settings, so it's tough for me to troubleshoot.

**Comment by hdgarrood** [comment]
I've fixed it - apparently the `deploy_key` option needs to point to a file which contains the key, you can't just put the key in the environment variable directly. I followed [Travis' guide to adding encrypted files](https://docs.travis-ci.com/user/encrypting-files/) and added `deploy_key.enc` to the repo. This now seems to be working, but the book.purescript.org link is no longer working because the CNAME file doesn't appear to have made it across into the `gh-pages` branch.

**Comment by milesfrain** [comment]
> the CNAME file doesn't appear to have made it across into the `gh-pages` branch

Did a quick commit (or two) to fix this.
Looks like it's working now.

**Comment by hdgarrood** [comment]
Oh, I've just spotted that the README is no longer present in the rendered HTML - can we configure mdbook to include it?

**Comment by milesfrain** [comment]
Fixed with #86

**Pull request merged**
