### PR TITLE
Clarify wording in Chapter 4 problem descriptions

### PR DESCRIPTION
**Pull request by a-robu**
Hi everyone!

I'm a PS beginner and I'm working my way through the book. There are two exercises which I found confusing.

> (Medium) Write a function triples :: Int -> Array (Array Int) which takes a number n and calculates all Pythagorean triples whose components are less than or equal to n. A Pythagorean triple is an array of numbers [a, b, c] such that a² + b² = c². Hint: Use the guard function in an array comprehension.

Here, it wasn't clear to me if the word "components" referred to the terms of the equation (a², b², etc) or the values "a", "b" and "c", so I am proposing making reference this explicit.

> (Difficult) Write a function factorizations which produces all factorizations of an integer n, i.e. arrays of integers whose product is n. Hint: for an integer greater than 1, break the problem down into two subproblems: finding the first factor, and finding the remaining factors.

The problem definition here is ambiguous. It sounds like it's asking for all possible factorisation of an integer, of which there are many (e.g.: 20 can be 2x2x5 but also 4x5). I am changing the problem description to make it clear that it is asking for the prime factorisation. I am also renaming the function to `factorize` which I think is how this step is named in Mathematics.

Also somewhat relevant to this pull request is that I started taking notes of my thoughts as I am reading the book [on discourse](https://discourse.purescript.org/t/my-experience-as-a-ps-beginner-learning-from-the-purescript-by-example-book/1667/2). If you find them useful, let me know.

Best wishes.

### CODE REVIEW

**Comment by milesfrain** [comment]
Thanks. These PRs are a great way to improve the quality of the book and make exercises a lot easier for folks.

I like your book notes too, and will try to address the points you list. Feel free to make more PRs if I'm slow to editing those sections myself.

**Comment by hdgarrood** [comment]
I don't think the problem definition is ambiguous; it is indeed asking for all possible factorizations, so its type should be `Int -> Array (Array Int)`, and the result of `factorizations 20` should include `[2,2,5]` as well as `[4,5]`. I think the exercise as stated previously makes more sense in the context of teaching do notation; the problem was really that the solutions misunderstood what the exercise was asking you to do and were solving a different problem (i.e. prime factorization).

**Comment by hdgarrood** [comment]
Thanks @a-robu for those notes! It's really handy to get that insight into what it's like to read through the book as a beginner.

> I like your book notes too, and will try to address the points you list.

I just think it's worth noting that it's usually not a good thing in beginner materials to address every possible confusion that someone might have, and actually I think a lot of those notes probably _shouldn't_ lead to changes in the book; it's simply not possible to build up a bulletproof intuition for everything immediately. Rather, the goal should be to help the reader build up a good enough mental model _for now_ so that they can keep making progress. There should be some work done to help the reader avoid misleading intuitions, but not too much - because otherwise we'll get bogged down in details which are unimportant to the reader at their current stage.

**Comment by a-robu** [comment]
> I don't think the problem definition is ambiguous; it is indeed asking for all possible factorizations

Whoops, sorry about that. I would offer to help fix this but I think it's better if I leave it be for now.

> It's really handy to get that insight into what it's like to read through the book as a beginner.

Great, that's what I hoped to achieve. I've always found it very useful, when writing, to know what my audience is thinking.

**Comment by milesfrain** [comment]
Many of the solutions are contributed by readers, so definitely look at them with skepticism. I missed this one during review. Glad you're reading more closely. Filed #208 to follow-up, but it doesn't seem too urgent.

**Pull request merged**
